export interface ICad_clie  {
nome: string,
 apelido: string,		
 fis_jur: string, 
 cpf: string, 
 rg: string, 
 contrib: string,
 email_fiscal: string,
 email: string,
 senha: string, 
 observacoes: string, 
 historico: string, 
 bloq_motivo: string, 
 obs_bancaria: string, 
 obs_comercial1: string, 
 obs_comercial2: string, 
 obs_comercial3: string, 
 obs_pessoal: string, 
 endereco: string, 
 numero: string, 
 complemento:string,
 bairro: string, 
 cidade: string, 
 estado: string, 
 cep: string, 
 telefone_res: string, 
 celular: string,
 data_cadastro: string, 
 consumidor_final: string, 
 ativo: string,
 no_site: string	
 data_recad:string
 }